/*
 * ktc_intrinsic.h — KotlinToC compiler intrinsics
 *
 * Stack-first. No GC. No hidden allocations.
 * Include this in every file generated by ktc.
 */
#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <errno.h>
#if defined(_WIN32)
    #include <windows.h>
#endif
#include <time.h>

/* ═══════════════════════════ Kotlin numeric type aliases ═════════════════ */
typedef int8_t   ktc_Byte;
typedef int16_t  ktc_Short;
typedef int32_t  ktc_Int;
typedef int64_t  ktc_Long;
typedef float    ktc_Float;
typedef double   ktc_Double;
typedef bool     ktc_Bool;
typedef char     ktc_Char;
typedef uint8_t  ktc_UByte;
typedef uint16_t ktc_UShort;
typedef uint32_t ktc_UInt;
typedef uint64_t ktc_ULong;

/* ═══════════════════════════ time ═══════════════════════════ */
uint64_t ktc_time_ms(void);
double ktc_time_seconds(void);
void ktc_time_sleep_seconds(double seconds);
void ktc_time_sleep_ms(uint32_t ms);

/* ═══════════════════════════ random ═══════════════════════════ */
#define KTC_RAND_MAX UINT32_MAX  // 4294967295

void ktc_srand(uint64_t seed);
uint32_t ktc_rand(void);
uint32_t ktc_rand_range(uint32_t bound);

/* ═══════════════════════════ alloca compat ═══════════════════════════ */
#if defined(_MSC_VER)
    #include <malloc.h>
    #define ktc_alloca(size) _alloca(size)

#elif defined(__clang__) || defined(__GNUC__)
    #define ktc_alloca(size) __builtin_alloca(size)

#elif defined(__has_builtin)
    #if __has_builtin(__builtin_alloca)
        #define ktc_alloca(size) __builtin_alloca(size)
    #endif

#endif

#ifndef ktc_alloca
    #include <alloca.h>
    #define ktc_alloca(size) alloca(size)
#endif

/* ═══════════════════════════ Array Trampoline ════════════════════════ */
/* Pass-by-value semantics for variable-size arrays.
 * Functions receive this struct, then copy data to a local stack buffer. */
typedef struct { int32_t size; void* data; } ktc_ArrayTrampoline;

/* ═══════════════════════════ Optional ════════════════════════════════ */
typedef enum { ktc_NONE = 0, ktc_SOME = 1 } ktc_OptionalTag;

typedef struct { ktc_OptionalTag tag; ktc_Byte   value; } ktc_Byte_Optional;
typedef struct { ktc_OptionalTag tag; ktc_Short  value; } ktc_Short_Optional;
typedef struct { ktc_OptionalTag tag; ktc_Int    value; } ktc_Int_Optional;
typedef struct { ktc_OptionalTag tag; ktc_Long   value; } ktc_Long_Optional;
typedef struct { ktc_OptionalTag tag; ktc_Float  value; } ktc_Float_Optional;
typedef struct { ktc_OptionalTag tag; ktc_Double value; } ktc_Double_Optional;
typedef struct { ktc_OptionalTag tag; ktc_Bool   value; } ktc_Bool_Optional;
typedef struct { ktc_OptionalTag tag; ktc_Char   value; } ktc_Char_Optional;
typedef struct { ktc_OptionalTag tag; ktc_UByte  value; } ktc_UByte_Optional;
typedef struct { ktc_OptionalTag tag; ktc_UShort value; } ktc_UShort_Optional;
typedef struct { ktc_OptionalTag tag; ktc_UInt   value; } ktc_UInt_Optional;
typedef struct { ktc_OptionalTag tag; ktc_ULong  value; } ktc_ULong_Optional;
typedef struct { ktc_OptionalTag tag; void*      value; } ktc_Ptr_Optional;
typedef struct { ktc_OptionalTag tag; ktc_Int    size; void* data; } ktc_Array_Optional;

/* ═══════════════════════════ Memory tracking ═════════════════════════ */
/*
 * Enabled by #define KTC_MEM_TRACK before including this header.
 * Intercepts malloc/calloc/realloc/free via macros.
 * Call ktc_mem_report() at program exit to print alloc/free summary + leaks.
 */

#ifdef KTC_MEM_TRACK

#ifndef KTC_MEM_MAX
#define KTC_MEM_MAX 8192
#endif

typedef struct {
    void*       ptr;
    size_t      size;
    const char* file;
    int         line;
    bool        active;   /* true = still allocated */
} ktc_MemRecord;

static ktc_MemRecord ktc_mem_records[KTC_MEM_MAX];
static int32_t ktc_mem_count    = 0;
static int32_t ktc_mem_allocs   = 0;
static int32_t ktc_mem_frees    = 0;
static size_t  ktc_mem_bytes    = 0;   /* current live bytes */

static inline void ktc_mem_record_alloc(void* p, size_t sz, const char* file, int line) {
    ktc_mem_allocs++;
    ktc_mem_bytes += sz;
    if (ktc_mem_count < KTC_MEM_MAX) {
        ktc_mem_records[ktc_mem_count++] = (ktc_MemRecord){p, sz, file, line, true};
    }
}

static inline void* ktc_malloc(size_t sz, const char* file, int line) {
    void* p = (malloc)(sz);
    ktc_mem_record_alloc(p, sz, file, line);
    return p;
}

static inline void* ktc_calloc(size_t n, size_t sz, const char* file, int line) {
    void* p = (calloc)(n, sz);
    ktc_mem_record_alloc(p, n * sz, file, line);
    return p;
}

static inline void* ktc_realloc(void* old, size_t sz, const char* file, int line) {
    /* mark old allocation as freed */
    for (int i = ktc_mem_count - 1; i >= 0; i--) {
        if (ktc_mem_records[i].ptr == old && ktc_mem_records[i].active) {
            ktc_mem_records[i].active = false;
            ktc_mem_bytes -= ktc_mem_records[i].size;
            ktc_mem_frees++;
            break;
        }
    }
    void* p = (realloc)(old, sz);
    ktc_mem_record_alloc(p, sz, file, line);
    return p;
}

static inline void ktc_free(void* p, const char* file, int line) {
    if (!p) return;
    for (int i = ktc_mem_count - 1; i >= 0; i--) {
        if (ktc_mem_records[i].ptr == p && ktc_mem_records[i].active) {
            ktc_mem_records[i].active = false;
            ktc_mem_bytes -= ktc_mem_records[i].size;
            ktc_mem_frees++;
            (free)(p);
            return;
        }
    }
    /* unknown or double-free */
    printf("[mem] WARNING: free(%p) unknown pointer at %s:%d\n", p, file, line);
    ktc_mem_frees++;
    (free)(p);
}

static inline void ktc_mem_report(void) {
    int leaks = 0;
    size_t leaked_bytes = 0;
    printf("\n====== ktc memory report ======\n");
    printf("  total allocs : %d\n", ktc_mem_allocs);
    printf("  total frees  : %d\n", ktc_mem_frees);
    printf("  balance      : %d\n", ktc_mem_allocs - ktc_mem_frees);
    for (int i = 0; i < ktc_mem_count; i++) {
        if (ktc_mem_records[i].active) {
            if (leaks == 0) printf("\n  LEAKS:\n");
            printf("    %p  %6zu bytes  %s:%d\n",
                ktc_mem_records[i].ptr, ktc_mem_records[i].size,
                ktc_mem_records[i].file, ktc_mem_records[i].line);
            leaks++;
            leaked_bytes += ktc_mem_records[i].size;
        }
    }
    if (leaks == 0) {
        printf("  status       : OK, no leaks\n");
    } else {
        printf("  leaked       : %d allocs, %zu bytes\n", leaks, leaked_bytes);
    }
    printf("===============================\n");
}

/* Macro overrides — must come AFTER the tracking functions */
#define malloc(sz)        ktc_malloc(sz, __FILE__, __LINE__)
#define calloc(n, sz)     ktc_calloc(n, sz, __FILE__, __LINE__)
#define realloc(p, sz)    ktc_realloc(p, sz, __FILE__, __LINE__)
#define free(p)           ktc_free(p, __FILE__, __LINE__)

#endif /* KTC_MEM_TRACK */

/* ═══════════════════════════ String ══════════════════════════════════ */

typedef struct {
    const char* ptr;
    int32_t     len;
} ktc_String;

typedef struct { ktc_OptionalTag tag; ktc_String value; } ktc_String_Optional;

/* String from literal — zero-cost, points into static storage. */
#define ktc_str(s) ((ktc_String){(s), (int32_t)(sizeof(s) - 1)})

/* String from pointer + length (no copy). */
static inline ktc_String ktc_string_wrap(const char* p, int32_t n) {
    return (ktc_String){p, n};
}

/* String equality. */
static inline bool ktc_string_eq(ktc_String a, ktc_String b) {
    return a.len == b.len && memcmp(a.ptr, b.ptr, (size_t)a.len) == 0;
}

/* String comparison (lexicographic). Returns <0, 0, or >0. */
static inline int ktc_string_cmp(ktc_String a, ktc_String b) {
    int32_t minlen = (a.len < b.len) ? a.len : b.len;
    int r = memcmp(a.ptr, b.ptr, (size_t)minlen);
    if (r != 0) return r;
    return (a.len > b.len) - (a.len < b.len);
}

/* Concatenate two strings into a caller-provided buffer.
 * Usage:  char buf[256]; ktc_String s = ktc_string_cat(buf, sizeof(buf), a, b);
 */
static inline ktc_String ktc_string_cat(char* buf, int bufsz, ktc_String a, ktc_String b) {
    int32_t total = a.len + b.len;
    if (total >= bufsz) total = bufsz - 1;
    memcpy(buf, a.ptr, (size_t)a.len);
    int32_t rest = total - a.len;
    memcpy(buf + a.len, b.ptr, (size_t)rest);
    buf[total] = '\0';
    return (ktc_String){buf, total};
}

/* Substring — returns a view into the original string (no copy).
 * substring(from) and substring(from, to) Kotlin semantics. */
static inline ktc_String ktc_string_substring(ktc_String s, int32_t from, int32_t to) {
    if (from < 0) from = 0;
    if (to > s.len) to = s.len;
    if (from >= to) return (ktc_String){"", 0};
    return (ktc_String){s.ptr + from, to - from};
}

/* ═══════════════════════════ String Builder ══════════════════════════ */

typedef struct {
    char*   ptr;
    int32_t len;
    int32_t cap;
} ktc_StrBuf;

/* Stack-backed string builder: char buf[256]; ktc_StrBuf sb = {buf, 0, 256}; */

static inline ktc_String ktc_sb_to_string(ktc_StrBuf* sb) {
    return (ktc_String){sb->ptr, sb->len};
}

static inline void ktc_sb_append_str(ktc_StrBuf* sb, ktc_String s) {
    int32_t n = s.len;
    if (sb->len + n > sb->cap) n = sb->cap - sb->len;
    if (n <= 0) return;
    memcpy(sb->ptr + sb->len, s.ptr, (size_t)n);
    sb->len += n;
}

static inline void ktc_sb_append_cstr(ktc_StrBuf* sb, const char* s) {
    ktc_sb_append_str(sb, (ktc_String){s, (int32_t)strlen(s)});
}

static inline void ktc_sb_append_char(ktc_StrBuf* sb, char c) {
    if (sb->len < sb->cap) sb->ptr[sb->len++] = c;
}

static inline void ktc_sb_append_int(ktc_StrBuf* sb, int32_t v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRId32, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void ktc_sb_append_long(ktc_StrBuf* sb, int64_t v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRId64, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void ktc_sb_append_double(ktc_StrBuf* sb, double v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%f", v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void ktc_sb_append_bool(ktc_StrBuf* sb, bool v) {
    ktc_sb_append_cstr(sb, v ? "true" : "false");
}

static inline void ktc_sb_append_byte(ktc_StrBuf* sb, ktc_Byte v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRId8, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void ktc_sb_append_short(ktc_StrBuf* sb, ktc_Short v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRId16, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void ktc_sb_append_ubyte(ktc_StrBuf* sb, ktc_UByte v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRIu8, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void ktc_sb_append_ushort(ktc_StrBuf* sb, ktc_UShort v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRIu16, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void ktc_sb_append_uint(ktc_StrBuf* sb, ktc_UInt v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRIu32, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void ktc_sb_append_ulong(ktc_StrBuf* sb, ktc_ULong v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRIu64, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

/* ═══════════════════════════ Hash helpers (for monomorphized HashMap) */

static inline int32_t ktc_hash_i8(int8_t v)    { return (int32_t)v; }
static inline int32_t ktc_hash_i16(int16_t v)  { return (int32_t)v; }
static inline int32_t ktc_hash_i32(int32_t v)  { return (int32_t)(uint32_t)v; }
static inline int32_t ktc_hash_i64(int64_t v)  { uint64_t u = (uint64_t)v; return (int32_t)(uint32_t)(u ^ (u >> 32)); }
static inline int32_t ktc_hash_f32(float v)    { uint32_t b; memcpy(&b, &v, 4); return (int32_t)b; }
static inline int32_t ktc_hash_f64(double v)   { uint64_t b; memcpy(&b, &v, 8); return (int32_t)(uint32_t)(b ^ (b >> 32)); }
static inline int32_t ktc_hash_bool(bool v)    { return v ? 1 : 0; }
static inline int32_t ktc_hash_char(char v)    { return (int32_t)(unsigned char)v; }
static inline int32_t ktc_hash_u8(uint8_t v)   { return (int32_t)(uint32_t)v; }
static inline int32_t ktc_hash_u16(uint16_t v) { return (int32_t)(uint32_t)v; }
static inline int32_t ktc_hash_u32(uint32_t v) { return (int32_t)v; }
static inline int32_t ktc_hash_u64(uint64_t v) { return (int32_t)(uint32_t)(v ^ (v >> 32)); }
static inline int32_t ktc_hash_str(ktc_String s) {
    uint32_t h = 2166136261u;
    for (int32_t i = 0; i < s.len; i++) { h ^= (uint8_t)s.ptr[i]; h *= 16777619u; }
    return (int32_t)h;
}

/* ═══════════════════════════ Conversion helpers ═════════════════════ */

static inline ktc_String ktc_int_to_string(char* buf, int bufsz, int32_t v) {
    int n = snprintf(buf, (size_t)bufsz, "%" PRId32, v);
    return (ktc_String){buf, n};
}

static inline ktc_String ktc_long_to_string(char* buf, int bufsz, int64_t v) {
    int n = snprintf(buf, (size_t)bufsz, "%" PRId64, v);
    return (ktc_String){buf, n};
}

static inline ktc_String ktc_double_to_string(char* buf, int bufsz, double v) {
    int n = snprintf(buf, (size_t)bufsz, "%f", v);
    return (ktc_String){buf, n};
}

static inline ktc_String ktc_bool_to_string(bool v) {
    return v ? ktc_str("true") : ktc_str("false");
}

/* ═══════════════════════════ String → Number parsing ═════════════════ */

/* Parse ktc_String to int32_t (simple atoi-like, stops at non-digit). */
static inline int32_t ktc_str_toInt(ktc_String s) {
    char buf[32];
    int32_t n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    return (int32_t)atoi(buf);
}

/* Parse ktc_String to int64_t. */
static inline int64_t ktc_str_toLong(ktc_String s) {
    char buf[32];
    int32_t n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    return (int64_t)atoll(buf);
}

/* Parse ktc_String to double. */
static inline double ktc_str_toDouble(ktc_String s) {
    char buf[64];
    int32_t n = s.len < 63 ? s.len : 63;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    return strtod(buf, NULL);
}

/* ═══════════════════ String → Number nullable parsing ════════════════ */

/* Parse ktc_String to int32_t, returning false on failure. */
static inline bool ktc_str_toIntOrNull(ktc_String s, int32_t* out) {
    if (s.len == 0) return false;
    char buf[32];
    int32_t n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    char* end;
    long v = strtol(buf, &end, 10);
    if (end == buf || *end != '\0') return false;
    *out = (int32_t)v;
    return true;
}

/* Parse ktc_String to int64_t, returning false on failure. */
static inline bool ktc_str_toLongOrNull(ktc_String s, int64_t* out) {
    if (s.len == 0) return false;
    char buf[32];
    int32_t n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    char* end;
    long long v = strtoll(buf, &end, 10);
    if (end == buf || *end != '\0') return false;
    *out = (int64_t)v;
    return true;
}

/* Parse ktc_String to double, returning false on failure. */
static inline bool ktc_str_toDoubleOrNull(ktc_String s, double* out) {
    if (s.len == 0) return false;
    char buf[64];
    int32_t n = s.len < 63 ? s.len : 63;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    char* end;
    double v = strtod(buf, &end);
    if (end == buf || *end != '\0') return false;
    *out = v;
    return true;
}
