/*
 * ktc_runtime.h — KotlinToC minimal C11 runtime
 *
 * Stack-first. No GC. No hidden allocations.
 * Include this in every file generated by ktc.
 */
#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>

/* ═══════════════════════════ String ══════════════════════════════════ */

typedef struct {
    const char* ptr;
    int32_t     len;
} kt_String;

/* String from literal — zero-cost, points into static storage. */
#define kt_str(s) ((kt_String){(s), (int32_t)(sizeof(s) - 1)})

/* String from pointer + length (no copy). */
static inline kt_String kt_string_wrap(const char* p, int32_t n) {
    return (kt_String){p, n};
}

/* String equality. */
static inline bool kt_string_eq(kt_String a, kt_String b) {
    return a.len == b.len && memcmp(a.ptr, b.ptr, (size_t)a.len) == 0;
}

/* String comparison (lexicographic). Returns <0, 0, or >0. */
static inline int kt_string_cmp(kt_String a, kt_String b) {
    int32_t minlen = (a.len < b.len) ? a.len : b.len;
    int r = memcmp(a.ptr, b.ptr, (size_t)minlen);
    if (r != 0) return r;
    return (a.len > b.len) - (a.len < b.len);
}

/* Concatenate two strings into a caller-provided buffer.
 * Usage:  char buf[256]; kt_String s = kt_string_cat(buf, sizeof(buf), a, b);
 */
static inline kt_String kt_string_cat(char* buf, int bufsz, kt_String a, kt_String b) {
    int32_t total = a.len + b.len;
    if (total >= bufsz) total = bufsz - 1;
    memcpy(buf, a.ptr, (size_t)a.len);
    int32_t rest = total - a.len;
    memcpy(buf + a.len, b.ptr, (size_t)rest);
    buf[total] = '\0';
    return (kt_String){buf, total};
}

/* ═══════════════════════════ String Builder ══════════════════════════ */

typedef struct {
    char*   ptr;
    int32_t len;
    int32_t cap;
} kt_StrBuf;

/* Stack-backed string builder: char buf[256]; kt_StrBuf sb = {buf, 0, 256}; */

static inline kt_String kt_sb_to_string(kt_StrBuf* sb) {
    return (kt_String){sb->ptr, sb->len};
}

static inline void kt_sb_append_str(kt_StrBuf* sb, kt_String s) {
    int32_t n = s.len;
    if (sb->len + n > sb->cap) n = sb->cap - sb->len;
    if (n <= 0) return;
    memcpy(sb->ptr + sb->len, s.ptr, (size_t)n);
    sb->len += n;
}

static inline void kt_sb_append_cstr(kt_StrBuf* sb, const char* s) {
    kt_sb_append_str(sb, (kt_String){s, (int32_t)strlen(s)});
}

static inline void kt_sb_append_char(kt_StrBuf* sb, char c) {
    if (sb->len < sb->cap) sb->ptr[sb->len++] = c;
}

static inline void kt_sb_append_int(kt_StrBuf* sb, int32_t v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRId32, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void kt_sb_append_long(kt_StrBuf* sb, int64_t v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%" PRId64, v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void kt_sb_append_double(kt_StrBuf* sb, double v) {
    int32_t rem = sb->cap - sb->len;
    if (rem <= 0) return;
    int n = snprintf(sb->ptr + sb->len, (size_t)rem, "%f", v);
    if (n > 0) sb->len += ((int32_t)n < rem) ? (int32_t)n : rem - 1;
}

static inline void kt_sb_append_bool(kt_StrBuf* sb, bool v) {
    kt_sb_append_cstr(sb, v ? "true" : "false");
}

/* ═══════════════════════════ Arena allocator ═════════════════════════ */

#ifndef KT_ARENA_SIZE
#define KT_ARENA_SIZE (64 * 1024)   /* 64 KiB default */
#endif

typedef struct {
    char    buf[KT_ARENA_SIZE];
    size_t  off;
} kt_Arena;

static inline void kt_arena_init(kt_Arena* a) {
    a->off = 0;
}

static inline void* kt_arena_alloc(kt_Arena* a, size_t n) {
    size_t aligned = (n + 7u) & ~(size_t)7u;
    if (a->off + aligned > KT_ARENA_SIZE) {
        fprintf(stderr, "kt_Arena: out of memory (%zu requested, %zu/%d used)\n",
                n, a->off, KT_ARENA_SIZE);
        abort();
    }
    void* p = a->buf + a->off;
    a->off += aligned;
    return p;
}

static inline void kt_arena_reset(kt_Arena* a) {
    a->off = 0;
}

/* Allocate a string in the arena (copies data). */
static inline kt_String kt_arena_string(kt_Arena* a, const char* p, int32_t len) {
    char* dst = (char*)kt_arena_alloc(a, (size_t)len + 1);
    memcpy(dst, p, (size_t)len);
    dst[len] = '\0';
    return (kt_String){dst, len};
}

/* Arena-backed string builder. */
static inline kt_StrBuf kt_sb_arena(kt_Arena* a, int32_t cap) {
    return (kt_StrBuf){(char*)kt_arena_alloc(a, (size_t)cap), 0, cap};
}

/* ═══════════════════════════ HashMap support ═════════════════════════ */

/* Generic map metadata — shared across all HashMap key:value types. */
typedef struct {
    bool*    occ;   /* occupancy bitmap (parallel to keys/vals arrays) */
    int32_t  cap;   /* capacity */
    int32_t  len;   /* number of entries */
} kt_MapInfo;

static inline void kt_map_clear(kt_MapInfo* m) {
    memset(m->occ, 0, (size_t)m->cap * sizeof(bool));
    m->len = 0;
}

static inline void kt_map_free(void* keys, void* vals, kt_MapInfo* m) {
    free(keys); free(vals); free(m->occ);
    m->occ = NULL; m->cap = 0; m->len = 0;
}

/* FNV-1a hash for kt_String keys. */
static inline uint32_t kt_map_strhash(kt_String s) {
    uint32_t h = 2166136261u;
    for (int32_t i = 0; i < s.len; i++) { h ^= (uint8_t)s.ptr[i]; h *= 16777619u; }
    return h;
}

/* ═══════════════════════════ Conversion helpers ═════════════════════ */

static inline kt_String kt_int_to_string(char* buf, int bufsz, int32_t v) {
    int n = snprintf(buf, (size_t)bufsz, "%" PRId32, v);
    return (kt_String){buf, n};
}

static inline kt_String kt_long_to_string(char* buf, int bufsz, int64_t v) {
    int n = snprintf(buf, (size_t)bufsz, "%" PRId64, v);
    return (kt_String){buf, n};
}

static inline kt_String kt_double_to_string(char* buf, int bufsz, double v) {
    int n = snprintf(buf, (size_t)bufsz, "%f", v);
    return (kt_String){buf, n};
}

static inline kt_String kt_bool_to_string(bool v) {
    return v ? kt_str("true") : kt_str("false");
}

/* ═══════════════════════════ String → Number parsing ═════════════════ */

/* Parse kt_String to int32_t (simple atoi-like, stops at non-digit). */
static inline int32_t kt_str_toInt(kt_String s) {
    char buf[32];
    int32_t n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    return (int32_t)atoi(buf);
}

/* Parse kt_String to int64_t. */
static inline int64_t kt_str_toLong(kt_String s) {
    char buf[32];
    int32_t n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    return (int64_t)atoll(buf);
}

/* Parse kt_String to double. */
static inline double kt_str_toDouble(kt_String s) {
    char buf[64];
    int32_t n = s.len < 63 ? s.len : 63;
    memcpy(buf, s.ptr, (size_t)n);
    buf[n] = '\0';
    return strtod(buf, NULL);
}
