/*
 * ktc_intrinsic.h — KotlinToC compiler intrinsics
 *
 * Stack-first. No GC. No hidden allocations.
 * Include this in every file generated by ktc.
 */
#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <errno.h>
#if defined(_WIN32)
    #include <windows.h>
#endif
#include <time.h>

/* ═══════════════════════════ Kotlin numeric type aliases ═════════════════ */
typedef int8_t   ktc_Byte;
typedef int16_t  ktc_Short;
typedef int32_t  ktc_Int;
typedef int64_t  ktc_Long;
typedef float    ktc_Float;
typedef double   ktc_Double;
typedef bool     ktc_Bool;
typedef char     ktc_Char;
typedef uint8_t  ktc_UByte;
typedef uint16_t ktc_UShort;
typedef uint32_t ktc_UInt;
typedef uint64_t ktc_ULong;

/* ═══════════════════════════ time ═══════════════════════════ */
ktc_ULong ktc_time_ms(void);
ktc_Double ktc_time_seconds(void);
void ktc_time_sleep_seconds(ktc_Double seconds);
void ktc_time_sleep_ms(ktc_UInt ms);

/* ═══════════════════════════ random ═══════════════════════════ */
#define KTC_RAND_MAX UINT32_MAX  // 4294967295

void ktc_srand(ktc_ULong seed);
ktc_UInt ktc_rand(void);
ktc_UInt ktc_rand_range(ktc_UInt bound);

/* ═══════════════════════════ alloca compat ═══════════════════════════ */
#if defined(_MSC_VER)
    #include <malloc.h>
    #define ktc_alloca(size) _alloca(size)

#elif defined(__clang__) || defined(__GNUC__)
    #define ktc_alloca(size) __builtin_alloca(size)

#elif defined(__has_builtin)
    #if __has_builtin(__builtin_alloca)
        #define ktc_alloca(size) __builtin_alloca(size)
    #endif

#endif

#ifndef ktc_alloca
    #include <alloca.h>
    #define ktc_alloca(size) alloca(size)
#endif

/* ═══════════════════════════ Array Trampoline ════════════════════════ */
/* Pass-by-value semantics for variable-size arrays.
 * Functions receive this struct, then copy data to a local stack buffer. */
typedef struct { ktc_Int size; void* data; } ktc_ArrayTrampoline;

/* ═══════════════════════════ Optional ════════════════════════════════ */
typedef enum { ktc_NONE = 0, ktc_SOME = 1 } ktc_OptionalTag;

#define KTC_OPTIONAL(T) typedef struct { ktc_OptionalTag tag; T value; } T##_Optional

KTC_OPTIONAL(ktc_Byte);
KTC_OPTIONAL(ktc_Short);
KTC_OPTIONAL(ktc_Int);
KTC_OPTIONAL(ktc_Long);
KTC_OPTIONAL(ktc_Float);
KTC_OPTIONAL(ktc_Double);
KTC_OPTIONAL(ktc_Bool);
KTC_OPTIONAL(ktc_Char);
KTC_OPTIONAL(ktc_UByte);
KTC_OPTIONAL(ktc_UShort);
KTC_OPTIONAL(ktc_UInt);
KTC_OPTIONAL(ktc_ULong);

/* ═══════════════════════════ Memory tracking ═════════════════════════ */
/*
 * Enabled by #define KTC_MEM_TRACK before including this header.
 * Intercepts malloc/calloc/realloc/free via macros.
 * Call ktc_mem_report() at program exit to print alloc/free summary + leaks.
 */

#ifdef KTC_MEM_TRACK

#ifndef KTC_MEM_MAX
#define KTC_MEM_MAX 8192
#endif

typedef struct {
    void*           ptr;
    ktc_ULong       size;
    const ktc_Char* file;
    ktc_Int         line;
    ktc_Bool        active;   /* true = still allocated */
} ktc_MemRecord;

static ktc_MemRecord ktc_mem_records[KTC_MEM_MAX];
static ktc_Int ktc_mem_count    = 0;
static ktc_Int ktc_mem_allocs   = 0;
static ktc_Int ktc_mem_frees    = 0;
static ktc_ULong  ktc_mem_bytes = 0;   /* current live bytes */

static inline void ktc_mem_record_alloc(void* p, ktc_ULong sz, const ktc_Char* file, ktc_Int line) {
    ktc_mem_allocs++;
    ktc_mem_bytes += sz;
    if (ktc_mem_count < KTC_MEM_MAX) {
        ktc_mem_records[ktc_mem_count++] = (ktc_MemRecord){p, sz, file, line, true};
    }
}

static inline void* ktc_malloc(ktc_ULong sz, const ktc_Char* file, ktc_Int line) {
    void* p = (malloc)(sz);
    ktc_mem_record_alloc(p, sz, file, line);
    return p;
}

static inline void* ktc_calloc(ktc_ULong n, ktc_ULong sz, const ktc_Char* file, ktc_Int line) {
    void* p = (calloc)(n, sz);
    ktc_mem_record_alloc(p, n * sz, file, line);
    return p;
}

static inline void* ktc_realloc(void* old, ktc_ULong sz, const ktc_Char* file, ktc_Int line) {
    /* mark old allocation as freed */
    for (ktc_Int i = ktc_mem_count - 1; i >= 0; i--) {
        if (ktc_mem_records[i].ptr == old && ktc_mem_records[i].active) {
            ktc_mem_records[i].active = false;
            ktc_mem_bytes -= ktc_mem_records[i].size;
            ktc_mem_frees++;
            break;
        }
    }
    void* p = (realloc)(old, sz);
    ktc_mem_record_alloc(p, sz, file, line);
    return p;
}

static inline void ktc_free(void* p, const ktc_Char* file, ktc_Int line) {
    if (!p) return;
    for (ktc_Int i = ktc_mem_count - 1; i >= 0; i--) {
        if (ktc_mem_records[i].ptr == p && ktc_mem_records[i].active) {
            ktc_mem_records[i].active = false;
            ktc_mem_bytes -= ktc_mem_records[i].size;
            ktc_mem_frees++;
            (free)(p);
            return;
        }
    }
    /* unknown or double-free */
    printf("[mem] WARNING: free(%p) unknown pointer at %s:%d\n", p, file, line);
    ktc_mem_frees++;
    (free)(p);
}

static inline void ktc_mem_report(void) {
    ktc_Int leaks = 0;
    ktc_ULong leaked_bytes = 0;
    printf("\n====== ktc memory report ======\n");
    printf("  total allocs : %d\n", ktc_mem_allocs);
    printf("  total frees  : %d\n", ktc_mem_frees);
    printf("  balance      : %d\n", ktc_mem_allocs - ktc_mem_frees);
    for (ktc_Int i = 0; i < ktc_mem_count; i++) {
        if (ktc_mem_records[i].active) {
            if (leaks == 0) printf("\n  LEAKS:\n");
            printf("    %p  %6zu bytes  %s:%d\n",
                ktc_mem_records[i].ptr, ktc_mem_records[i].size,
                ktc_mem_records[i].file, ktc_mem_records[i].line);
            leaks++;
            leaked_bytes += ktc_mem_records[i].size;
        }
    }
    if (leaks == 0) {
        printf("  status       : OK, no leaks\n");
    } else {
        printf("  leaked       : %d allocs, %zu bytes\n", leaks, leaked_bytes);
    }
    printf("===============================\n");
}

/* Macro overrides — must come AFTER the tracking functions */
#define malloc(sz)        ktc_malloc(sz, __FILE__, __LINE__)
#define calloc(n, sz)     ktc_calloc(n, sz, __FILE__, __LINE__)
#define realloc(p, sz)    ktc_realloc(p, sz, __FILE__, __LINE__)
#define free(p)           ktc_free(p, __FILE__, __LINE__)

#endif /* KTC_MEM_TRACK */

/* ═══════════════════════════ String ══════════════════════════════════ */

typedef struct {
    const ktc_Char* ptr;
    ktc_Int     len;
} ktc_String;

typedef struct { ktc_OptionalTag tag; ktc_String value; } ktc_String_Optional;

/* String from literal — zero-cost, points into static storage. */
#define ktc_str(s) ((ktc_String){(s), (ktc_Int)(sizeof(s) - 1)})

/* String from pointer + length (no copy). */
static inline ktc_String ktc_string_wrap(const ktc_Char* p, ktc_Int n) {
    return (ktc_String){p, n};
}

/* String equality. */
static inline ktc_Bool ktc_string_eq(ktc_String a, ktc_String b) {
    return a.len == b.len && memcmp(a.ptr, b.ptr, (ktc_ULong)a.len) == 0;
}

/* String comparison (lexicographic). Returns <0, 0, or >0. */
static inline ktc_Int ktc_string_cmp(ktc_String a, ktc_String b) {
    ktc_Int minlen = (a.len < b.len) ? a.len : b.len;
    ktc_Int r = memcmp(a.ptr, b.ptr, (ktc_ULong)minlen);
    if (r != 0) return r;
    return (a.len > b.len) - (a.len < b.len);
}

/* Concatenate two strings into a caller-provided buffer.
 * Usage:  ktc_Char buf[256]; ktc_String s = ktc_string_cat(buf, sizeof(buf), a, b);
 */
static inline ktc_String ktc_string_cat(ktc_Char* buf, ktc_Int bufsz, ktc_String a, ktc_String b) {
    ktc_Int total = a.len + b.len;
    if (total >= bufsz) total = bufsz - 1;
    memcpy(buf, a.ptr, (ktc_ULong)a.len);
    ktc_Int rest = total - a.len;
    memcpy(buf + a.len, b.ptr, (ktc_ULong)rest);
    buf[total] = '\0';
    return (ktc_String){buf, total};
}

/* Substring — returns a view into the original string (no copy).
 * substring(from) and substring(from, to) Kotlin semantics. */
static inline ktc_String ktc_string_substring(ktc_String s, ktc_Int from, ktc_Int to) {
    if (from < 0) from = 0;
    if (to > s.len) to = s.len;
    if (from >= to) return (ktc_String){"", 0};
    return (ktc_String){s.ptr + from, to - from};
}

/* ═══════════════════════════ String Builder ══════════════════════════ */

typedef struct {
    ktc_Char*   ptr;
    ktc_Int len;
    ktc_Int cap;
} ktc_StrBuf;

/* Stack-backed string builder: ktc_Char buf[256]; ktc_StrBuf sb = {buf, 0, 256}; */

static inline ktc_String ktc_sb_to_string(ktc_StrBuf* sb) {
    return (ktc_String){sb->ptr, sb->len};
}

static inline void ktc_sb_append_str(ktc_StrBuf* sb, ktc_String s) {
    ktc_Int n = s.len;
    if (sb->len + n > sb->cap) n = sb->cap - sb->len;
    if (n <= 0) return;
    memcpy(sb->ptr + sb->len, s.ptr, (ktc_ULong)n);
    sb->len += n;
}

static inline void ktc_sb_append_cstr(ktc_StrBuf* sb, const ktc_Char* s) {
    ktc_sb_append_str(sb, (ktc_String){s, (ktc_Int)strlen(s)});
}

static inline void ktc_sb_append_char(ktc_StrBuf* sb, ktc_Char c) {
    if (sb->len < sb->cap) sb->ptr[sb->len++] = c;
}

static inline void ktc_sb_append_int(ktc_StrBuf* sb, ktc_Int v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%" PRId32, v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

static inline void ktc_sb_append_long(ktc_StrBuf* sb, ktc_Long v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%" PRId64, v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

static inline void ktc_sb_append_double(ktc_StrBuf* sb, ktc_Double v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%f", v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

static inline void ktc_sb_append_bool(ktc_StrBuf* sb, ktc_Bool v) {
    ktc_sb_append_cstr(sb, v ? "true" : "false");
}

static inline void ktc_sb_append_byte(ktc_StrBuf* sb, ktc_Byte v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%" PRId8, v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

static inline void ktc_sb_append_short(ktc_StrBuf* sb, ktc_Short v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%" PRId16, v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

static inline void ktc_sb_append_ubyte(ktc_StrBuf* sb, ktc_UByte v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%" PRIu8, v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

static inline void ktc_sb_append_ushort(ktc_StrBuf* sb, ktc_UShort v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%" PRIu16, v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

static inline void ktc_sb_append_uint(ktc_StrBuf* sb, ktc_UInt v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%" PRIu32, v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

static inline void ktc_sb_append_ulong(ktc_StrBuf* sb, ktc_ULong v) {
    ktc_Int rem = sb->cap - sb->len;
    if (rem <= 0) return;
    ktc_Int n = snprintf(sb->ptr + sb->len, (ktc_ULong)rem, "%" PRIu64, v);
    if (n > 0) sb->len += ((ktc_Int)n < rem) ? (ktc_Int)n : rem - 1;
}

/* ═══════════════════════════ Hash helpers (for monomorphized HashMap) */

static inline ktc_Int ktc_hash_i8(ktc_Byte v)    { return (ktc_Int)v; }
static inline ktc_Int ktc_hash_i16(ktc_Short v)  { return (ktc_Int)v; }
static inline ktc_Int ktc_hash_i32(ktc_Int v)  { return (ktc_Int)(ktc_UInt)v; }
static inline ktc_Int ktc_hash_i64(ktc_Long v)  { ktc_ULong u = (ktc_ULong)v; return (ktc_Int)(ktc_UInt)(u ^ (u >> 32)); }
static inline ktc_Int ktc_hash_f32(ktc_Float v)    { ktc_UInt b; memcpy(&b, &v, 4); return (ktc_Int)b; }
static inline ktc_Int ktc_hash_f64(ktc_Double v)   { ktc_ULong b; memcpy(&b, &v, 8); return (ktc_Int)(ktc_UInt)(b ^ (b >> 32)); }
static inline ktc_Int ktc_hash_bool(ktc_Bool v)    { return v ? 1 : 0; }
static inline ktc_Int ktc_hash_char(ktc_Char v)    { return (ktc_Int)(unsigned char)v; }
static inline ktc_Int ktc_hash_u8(ktc_UByte v)   { return (ktc_Int)(ktc_UInt)v; }
static inline ktc_Int ktc_hash_u16(ktc_UShort v) { return (ktc_Int)(ktc_UInt)v; }
static inline ktc_Int ktc_hash_u32(ktc_UInt v) { return (ktc_Int)v; }
static inline ktc_Int ktc_hash_u64(ktc_ULong v) { return (ktc_Int)(ktc_UInt)(v ^ (v >> 32)); }
static inline ktc_Int ktc_hash_str(ktc_String s) {
    ktc_UInt h = 2166136261u;
    for (ktc_Int i = 0; i < s.len; i++) { h ^= (ktc_UByte)s.ptr[i]; h *= 16777619u; }
    return (ktc_Int)h;
}

/* ═══════════════════════════ Conversion helpers ═════════════════════ */

static inline ktc_String ktc_int_to_string(ktc_Char* buf, ktc_Int bufsz, ktc_Int v) {
    ktc_Int n = snprintf(buf, (ktc_ULong)bufsz, "%" PRId32, v);
    return (ktc_String){buf, n};
}

static inline ktc_String ktc_long_to_string(ktc_Char* buf, ktc_Int bufsz, ktc_Long v) {
    ktc_Int n = snprintf(buf, (ktc_ULong)bufsz, "%" PRId64, v);
    return (ktc_String){buf, n};
}

static inline ktc_String ktc_double_to_string(ktc_Char* buf, ktc_Int bufsz, ktc_Double v) {
    ktc_Int n = snprintf(buf, (ktc_ULong)bufsz, "%f", v);
    return (ktc_String){buf, n};
}

static inline ktc_String ktc_bool_to_string(ktc_Bool v) {
    return v ? ktc_str("true") : ktc_str("false");
}

/* ═══════════════════════════ String → Number parsing ═════════════════ */

/* Parse ktc_String to ktc_Int (simple atoi-like, stops at non-digit). */
static inline ktc_Int ktc_str_toInt(ktc_String s) {
    ktc_Char buf[32];
    ktc_Int n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (ktc_ULong)n);
    buf[n] = '\0';
    return (ktc_Int)atoi(buf);
}

/* Parse ktc_String to ktc_Long. */
static inline ktc_Long ktc_str_toLong(ktc_String s) {
    ktc_Char buf[32];
    ktc_Int n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (ktc_ULong)n);
    buf[n] = '\0';
    return (ktc_Long)atoll(buf);
}

/* Parse ktc_String to double. */
static inline ktc_Double ktc_str_toDouble(ktc_String s) {
    ktc_Char buf[64];
    ktc_Int n = s.len < 63 ? s.len : 63;
    memcpy(buf, s.ptr, (ktc_ULong)n);
    buf[n] = '\0';
    return strtod(buf, NULL);
}

/* ═══════════════════ String → Number nullable parsing ════════════════ */

/* Parse ktc_String to ktc_Int, returning false on failure. */
static inline ktc_Bool ktc_str_toIntOrNull(ktc_String s, ktc_Int* out) {
    if (s.len == 0) return false;
    ktc_Char buf[32];
    ktc_Int n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (ktc_ULong)n);
    buf[n] = '\0';
    ktc_Char* end;
    long v = strtol(buf, &end, 10);
    if (end == buf || *end != '\0') return false;
    *out = (ktc_Int)v;
    return true;
}

/* Parse ktc_String to ktc_Long, returning false on failure. */
static inline ktc_Bool ktc_str_toLongOrNull(ktc_String s, ktc_Long* out) {
    if (s.len == 0) return false;
    ktc_Char buf[32];
    ktc_Int n = s.len < 31 ? s.len : 31;
    memcpy(buf, s.ptr, (ktc_ULong)n);
    buf[n] = '\0';
    ktc_Char* end;
    long long v = strtoll(buf, &end, 10);
    if (end == buf || *end != '\0') return false;
    *out = (ktc_Long)v;
    return true;
}

/* Parse ktc_String to double, returning false on failure. */
static inline ktc_Bool ktc_str_toDoubleOrNull(ktc_String s, ktc_Double* out) {
    if (s.len == 0) return false;
    ktc_Char buf[64];
    ktc_Int n = s.len < 63 ? s.len : 63;
    memcpy(buf, s.ptr, (ktc_ULong)n);
    buf[n] = '\0';
    ktc_Char* end;
    ktc_Double v = strtod(buf, &end);
    if (end == buf || *end != '\0') return false;
    *out = v;
    return true;
}
